version: "3"
services:
  devcontainer:
    ports:
      - 5001:5000
      - 5173:5173
    restart: unless-stopped
    privileged: true
    container_name: frigate
    # add groups from host for render, plugdev, video
    group_add:
      - "109" # render
      - "110" # render
      - "44" # video
      - "46" # plugdev
    shm_size: "256mb"
    build:
      context: .
      dockerfile: docker/main/Dockerfile
      # Use target devcontainer-trt for TensorRT dev
      target: devcontainer
    # deploy:
    #       resources:
    #           reservations:
    #               devices:
    #                   - driver: nvidia
    #                     count: 1
    #                     capabilities: [gpu]
    environment:
      YOLO_MODELS: yolov7-320
    # devices:
    # - /dev/bus/usb:/dev/bus/usb
    # - /dev/dri:/dev/dri # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - .:/workspace/frigate:cached
      - ./web/dist:/opt/frigate/web:cached
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./debug:/media/frigate
      # - /dev/bus/usb:/dev/bus/usb
    #
  emqx:
    container_name: emqx
    image: eclipse-mosquitto:1.6
    ports:
      - 1883:1883
  double-take:
      container_name: double-take
      image: jakowenko/double-take
      restart: unless-stopped
      ports:
        - 3000:3000
  deepstack:
    container_name: deepstack
    image: deepquestai/deepstack
    restart: unless-stopped
    environment:
      - VISION_FACE=True
      - VISION_DETECTION=True
      - MODE=High
    ports:
      - 5050:5000