audio:
  enabled: false
  enabled_in_config: null
  filters: null
  listen:
  - bark
  - speech
  - yell
  - scream
  max_not_heard: 30
  min_volume: 500
birdseye:
  enabled: false
  height: 720
  mode: !!python/object/apply:frigate.config.BirdseyeModeEnum
  - motion
  quality: 8
  restream: false
  width: 1280
cameras:
  test:
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://172.29.243.65:554
          roles:
            - detect
            - rtmp
            - record
    detect:
      height: 1080
      width: 1920
      fps: 60
  test2:
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://172.29.243.65:554
          roles:
            - detect
            - rtmp
            - record
    detect:
      annotation_offset: 0
      enabled: true
      fps: 60
      height: 1080
      max_disappeared: null
      stationary:
        interval: null
        max_frames:
          default: null
          objects: {}
        threshold: null
      width: 1920
    enabled: true
    ffmpeg:
      global_args:
      - -hide_banner
      - -loglevel
      - warning
      - -threads
      - '2'
      hwaccel_args: []
      input_args: preset-rtsp-generic
      inputs:
      - global_args: []
        hwaccel_args: []
        input_args: []
        path: rtsp://172.29.243.65:554
        roles:
        - !!python/object/apply:frigate.config.CameraRoleEnum
          - record
        - !!python/object/apply:frigate.config.CameraRoleEnum
          - detect
        - !!python/object/apply:frigate.config.CameraRoleEnum
          - rtmp
      output_args:
        detect:
        - -threads
        - '2'
        - -f
        - rawvideo
        - -pix_fmt
        - yuv420p
        record: preset-record-generic
        rtmp: preset-rtmp-generic
      retry_interval: 10.0
    live:
      height: 720
      quality: 8
      stream_name: ''
    motion: null
    mqtt:
      bounding_box: false
      crop: true
      enabled: true
      height: 500
      quality: 100
      required_zones: []
      timestamp: false
    name: null
    objects:
      filters: null
      mask: ''
      track:
      - person
    onvif:
      autotracking:
        enabled: false
        required_zones: []
        return_preset: home
        timeout: 10
        track:
        - person
      host: ''
      password: null
      port: 8000
      user: null
    record:
      enabled: false
      enabled_in_config: null
      events:
        objects: null
        post_capture: 5
        pre_capture: 5
        required_zones: []
        retain:
          default: 10.0
          mode: !!python/object/apply:frigate.config.RetainModeEnum
          - motion
          objects: {}
      expire_interval: 60
      retain:
        days: 0.0
        mode: !!python/object/apply:frigate.config.RetainModeEnum
        - all
      sync_on_startup: false
    rtmp:
      enabled: false
    snapshots:
      bounding_box: true
      clean_copy: true
      crop: false
      enabled: false
      height: null
      quality: 70
      required_zones: []
      retain:
        default: 10.0
        mode: !!python/object/apply:frigate.config.RetainModeEnum
        - motion
        objects: {}
      timestamp: false
    timestamp_style:
      color:
        blue: 255
        green: 255
        red: 255
      effect: null
      format: '%m/%d/%Y %H:%M:%S'
      position: !!python/object/apply:frigate.config.TimestampPositionEnum
      - tl
      thickness: 2
    ui:
      dashboard: true
      order: 0
    zones: {}
database:
  path: /config/frigate.db
detect:
  annotation_offset: 0
  enabled: true
  fps: 60
  height: 1080
  max_disappeared: null
  stationary:
    interval: null
    max_frames:
      default: null
      objects: {}
    threshold: null
  width: 1280
detectors:
  cpu:
    model: null
    type: cpu
environment_vars: {}
ffmpeg:
  global_args:
  - -hide_banner
  - -loglevel
  - warning
  - -threads
  - '2'
  hwaccel_args: []
  input_args: preset-rtsp-generic
  output_args:
    detect:
    - -threads
    - '2'
    - -f
    - rawvideo
    - -pix_fmt
    - yuv420p
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime
      1 -c:v copy -c:a aac
    rtmp: preset-rtmp-generic
  retry_interval: 10.0
go2rtc: {}
live:
  height: 720
  quality: 8
  stream_name: ''
logger:
  default: !!python/object/apply:frigate.config.LogLevelEnum
  - info
  logs: {}
model:
  height: 320
  input_pixel_format: !!python/object/apply:frigate.detectors.detector_config.PixelFormatEnum
  - rgb
  input_tensor: !!python/object/apply:frigate.detectors.detector_config.InputTensorEnum
  - nhwc
  labelmap: {}
  labelmap_path: /labelmap.txt
  model_type: !!python/object/apply:frigate.detectors.detector_config.ModelTypeEnum
  - ssd
  path: /edgetpu_model.tflite
  width: 320
motion: null
mqtt:
  client_id: frigate
  enabled: true
  host: ll
  password: null
  port: 30
  stats_interval: 60
  tls_ca_certs: null
  tls_client_cert: null
  tls_client_key: null
  tls_insecure: null
  topic_prefix: frigate
  user: null
objects:
  filters: null
  mask: ''
  track:
  - person
record:
  enabled: false
  enabled_in_config: null
  events:
    objects: null
    post_capture: 5
    pre_capture: 5
    required_zones: []
    retain:
      default: 10.0
      mode: !!python/object/apply:frigate.config.RetainModeEnum
      - motion
      objects: {}
  expire_interval: 60
  retain:
    days: 30.0
    mode: !!python/object/apply:frigate.config.RetainModeEnum
    - all
  sync_on_startup: false
rtmp:
  enabled: false
snapshots:
  bounding_box: true
  clean_copy: true
  crop: false
  enabled: false
  height: null
  quality: 70
  required_zones: []
  retain:
    default: 10.0
    mode: !!python/object/apply:frigate.config.RetainModeEnum
    - motion
    objects: {}
  timestamp: false
telemetry:
  network_interfaces:
  - eth
  - enp
  - eno
  - ens
  - wl
  - lo
  stats:
    amd_gpu_stats: true
    intel_gpu_stats: true
    network_bandwidth: false
  version_check: true
timestamp_style:
  color:
    blue: 255
    green: 255
    red: 255
  effect: null
  format: '%m/%d/%Y %H:%M:%S'
  position: !!python/object/apply:frigate.config.TimestampPositionEnum
  - tl
  thickness: 2
ui:
  date_style: !!python/object/apply:frigate.config.DateTimeStyleEnum
  - short
  live_mode: !!python/object/apply:frigate.config.LiveModeEnum
  - mse
  strftime_fmt: null
  time_format: !!python/object/apply:frigate.config.TimeFormatEnum
  - browser
  time_style: !!python/object/apply:frigate.config.DateTimeStyleEnum
  - medium
  timezone: null
  use_experimental: false
